name: commons
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  meta: ^1.16.0
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
