name: server
description: Game server for Tsoh with dart_frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  commons:
    path: ../commons  
  dart_frog: ^1.2.0
  dart_frog_web_socket: ^1.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  meta: ^1.16.0
  synchronized: ^3.3.1
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
